#!/bin/bash

cat > "cloud-config.yaml" <<EOF
#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDg9ILc/TTz3YVAj1NXC7baoygrrnj13WmkplX6y9bJqYt7yElUPsYI45nNUthUjFRVOi+CJFWrPLRGFjx6zkmHWKSCP1kMU1wZwg7Ah+86ohS1oY0YCUG+RBHi2rblt/LOrGtdi3nCtNbOIt7l8Y7Y7HOojVmP0zsIpGZej+/WVr/pOgk3t3UD6olSp9TTjymZkukFHFb4xgkR/e4OH0Cs8xA91htfEh/H8aTTKmRoAGBWXw6wn8k5SYYlVRoW23bN2rsl7YWidPzGZjUlv2ySFGHUk7t2t31PNn58FzGAYGYyfNpVbESp2NsDJfDTIV49qt+6TmVZOHF25a0y2KYJ christian@apontis.ch
EOF

sudo coreos-install -d /dev/sda -C stable -c cloud-config.yaml
sudo reboot

